export const EMAIL_DOMAINS: Array<string> = [
    'gmail.com',
    'gmail.ca',
    'yahoo.com',
    'hotmail.com',
    'gmail.de',
    'outlook.com',
    'mail.com',
    'yahoo.it',
    'icloud.com',
    'live.com',
    'msn.com',
    'yahoo.fr',
    'inbox.com',
    'aol.com',
    'zoho.com',
    'yahoo.de',
];